// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user-grpc.proto

package server

import (
	"context"

	"user-grpc/internal/logic"
	"user-grpc/internal/svc"
	"user-grpc/user-grpc"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user_grpc.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUser(ctx context.Context, in *user_grpc.GetUserRequest) (*user_grpc.GetUserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserServer) Login(ctx context.Context, in *user_grpc.LoginRequest) (*user_grpc.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) Register(ctx context.Context, in *user_grpc.RegisterRequest) (*user_grpc.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) UpdateUser(ctx context.Context, in *user_grpc.UpdateUserRequest) (*user_grpc.UpdateUserResponse, error) {
	l := logic.NewUpdateUserLogic(ctx, s.svcCtx)
	return l.UpdateUser(in)
}

func (s *UserServer) GetMyDetail(ctx context.Context, in *user_grpc.GetMyDetailRequest) (*user_grpc.GetMyDetailResponse, error) {
	l := logic.NewGetMyDetailLogic(ctx, s.svcCtx)
	return l.GetMyDetail(in)
}
