// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ArticleInfo struct {
	Id      int    `json:"id"`
	Title   string `json:"title"`
	Comtext string `json:"comtext"`
}

type ArticleReq struct {
	Id int `json:"id"`
}

type ArticlerResp struct {
	BaseResponse
	Data ArticleInfo `json:"data"`
}

type BaseResponse struct {
	Code    int         `json:"code"`    // 状态码：0=成功，其他失败
	Message string      `json:"message"` // 提示信息
	Data    interface{} `json:"data"`    // 真正的数据（任意类型）
}

type GetMyDetailReq struct {
}

type LoginReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Phone    string `json:"phone"`
}
