// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	article "goZeroApi/internal/handler/article"
	tools "goZeroApi/internal/handler/tools"
	user "goZeroApi/internal/handler/user"
	"goZeroApi/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取文章详情
				Method:  http.MethodGet,
				Path:    "/article/:id",
				Handler: article.ArticleDetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/article"),
	)

	server.AddRoutes(
		[]rest.Route{},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取图形验证码
				Method:  http.MethodGet,
				Path:    "/generate",
				Handler: tools.GenerateCaptchaHandler(serverCtx),
			},
			{
				// 校验图形验证码
				Method:  http.MethodPost,
				Path:    "/verify",
				Handler: tools.VerifyCaptchaHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/captcha"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/sendEmail",
				Handler: tools.SendEmailCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				// 用户注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取个人信息
				Method:  http.MethodPost,
				Path:    "/my/detail",
				Handler: user.GetMyDetailHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/user"),
	)
}
