// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user-grpc.proto

package user

import (
	"context"

	"user-grpc/user-grpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetMyDetailRequest  = user_grpc.GetMyDetailRequest
	GetMyDetailResponse = user_grpc.GetMyDetailResponse
	GetUserRequest      = user_grpc.GetUserRequest
	GetUserResponse     = user_grpc.GetUserResponse
	LoginRequest        = user_grpc.LoginRequest
	LoginResponse       = user_grpc.LoginResponse
	RegisterRequest     = user_grpc.RegisterRequest
	RegisterResponse    = user_grpc.RegisterResponse
	UpdateUserRequest   = user_grpc.UpdateUserRequest
	UpdateUserResponse  = user_grpc.UpdateUserResponse

	User interface {
		GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
		GetMyDetail(ctx context.Context, in *GetMyDetailRequest, opts ...grpc.CallOption) (*GetMyDetailResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	client := user_grpc.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultUser) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := user_grpc.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUser) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := user_grpc.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUser) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	client := user_grpc.NewUserClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

func (m *defaultUser) GetMyDetail(ctx context.Context, in *GetMyDetailRequest, opts ...grpc.CallOption) (*GetMyDetailResponse, error) {
	client := user_grpc.NewUserClient(m.cli.Conn())
	return client.GetMyDetail(ctx, in, opts...)
}
